### GET Pagina de inicio
GET http://localhost:1234

### GET Página de error
GET http://localhost:1234/404 

### GET Página logo
GET http://localhost:1234/logo.webp

### POST objeto con name, email y message
POST http://localhost:1234/contacto
Content-Type: application/json

{
    "name": "Ander",
    "email": "agibarguen@gmail.com",
    "message" : "Si lees esto que sepas que Iron Maiden > Metallica. De nada ;)"
}